joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50

joint3_controller:
    type: joint_path_tracking_controller/JointPathTrackingController
    joint: joint3