joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50

joint3_controller:
    type: joint_path_tracking_controller/JointPathTrackingController
    joints:
        - name: joint1
          min_pos: 0.0
          max_pos: 0.367
          min_speed: 0.001
          default_speed: 0.008
          max_speed: 0.012
          waypoint_tolerance: 0.005 #0.01745330
          goal_tolerance:     0.00001 #0.008726650

        - name: joint2
          min_pos_deg: 0.0
          max_pos_deg: 360.0
          min_rpm: 0.24
          default_rpm: 0.5
          max_rpm: 3.0
          waypoint_tolerance: 0.01745330
          goal_tolerance:     0.008726650
