transmissions:
  # transmission_3:
  #   joints:
  #     - joint3
  #   actuators:
  #     - linear_actuator_controller_actuator
  #   type: transmission_interface::SimpleTransmission
  transmission_1:
    joints:
      - joint1
    actuators:
      - linear_actuator_controller_actuator
    type: Linear_Actuator::Transmission_Loader
    package: linear_actuator_controller
    min_step_deg: 1.8
    micro_steps: 8
    lead: 0.008
  transmission_2:
    joints:
      - joint2
    actuators:
      - dynx_1
    type: transmission_interface::SimpleTransmission


  


